// Package fixture writes transcript files for tests. Every row copies the
// shape of a row Claude Code 2.1.251 to 2.1.287 wrote, with invented text;
// no real transcript is in the repository.
package fixture

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// Start is when a transcript's first row is stamped. Each row after it is a
// minute later unless At moves the clock.
var Start = time.Date(2026, 10, 1, 9, 0, 0, 0, time.UTC)

type Row = map[string]any

// Transcript builds the rows of one session in file order.
type Transcript struct {
	Rows []Row
	now  time.Time
	seq  int
}

func New() *Transcript {
	return &Transcript{now: Start}
}

// At stamps the rows that follow from t on.
func (t *Transcript) At(at time.Time) *Transcript {
	t.now = at
	return t
}

func (t *Transcript) id(prefix string) string {
	t.seq++
	return fmt.Sprintf("%s-%04d", prefix, t.seq)
}

func (t *Transcript) stamp() string {
	at := t.now
	t.now = t.now.Add(time.Minute)
	return at.Format("2006-01-02T15:04:05.000Z")
}

// Raw appends a row as given, with no time added.
func (t *Transcript) Raw(row Row) *Transcript {
	t.Rows = append(t.Rows, row)
	return t
}

func (t *Transcript) row(kind string, fields Row) Row {
	row := Row{"type": kind, "uuid": t.id("uuid"), "timestamp": t.stamp(), "isSidechain": false,
		"cwd": "/work/app", "gitBranch": "feat/thing", "sessionId": "fixture", "version": "2.1.287"}
	for k, v := range fields {
		row[k] = v
	}
	t.Rows = append(t.Rows, row)
	return row
}

// Prompt is a prompt the user typed.
func (t *Transcript) Prompt(text string) *Transcript {
	t.row("user", Row{"promptId": t.id("prompt"), "origin": Row{"kind": "human"}, "promptSource": "typed",
		"message": Row{"role": "user", "content": text}})
	return t
}

// Unsourced is a plain text row with no origin, as an older Claude Code
// wrote a prompt.
func (t *Transcript) Unsourced(text string) *Transcript {
	t.row("user", Row{"message": Row{"role": "user", "content": text}})
	return t
}

func command(name, args string) string {
	return fmt.Sprintf("<command-message>%s</command-message>\n<command-name>/%s</command-name>\n<command-args>%s</command-args>", name, name, args)
}

// Slash is a slash command the user typed that expands a skill found at dir.
func (t *Transcript) Slash(name, args, dir string) *Transcript {
	prompt := t.id("prompt")
	t.row("user", Row{"promptId": prompt, "origin": Row{"kind": "human"},
		"message": Row{"role": "user", "content": command(name, args)}})
	t.row("user", Row{"promptId": prompt, "isMeta": true, "turnCompanion": true,
		"message": Row{"role": "user", "content": []Row{{"type": "text", "text": "Base directory for this skill: " + dir + "\n\n# The skill's text"}}}})
	return t
}

// SlashOnly is a slash command row with nothing after it that belongs to it.
// It returns the prompt id the turn runs under.
func (t *Transcript) SlashOnly(name, args string) string {
	prompt := t.id("prompt")
	t.row("user", Row{"promptId": prompt, "message": Row{"role": "user", "content": command(name, args)}})
	return prompt
}

// Builtin is a command Claude Code handles itself: a caveat, the command,
// and its output, with no expansion.
func (t *Transcript) Builtin(name string) *Transcript {
	prompt := t.id("prompt")
	t.row("user", Row{"promptId": prompt, "isMeta": true,
		"message": Row{"role": "user", "content": "<local-command-caveat>Caveat: the messages below were generated by the user while running local commands.</local-command-caveat>"}})
	t.row("user", Row{"promptId": prompt, "message": Row{"role": "user", "content": command(name, "")}})
	t.row("user", Row{"promptId": prompt, "message": Row{"role": "user", "content": "<local-command-stdout>ok</local-command-stdout>"}})
	return t
}

func (t *Transcript) toolUse(name string, input Row) string {
	id := t.id("toolu")
	t.row("assistant", Row{"message": Row{"role": "assistant", "content": []Row{{"type": "tool_use", "id": id, "name": name, "input": input}}}})
	return id
}

func (t *Transcript) toolResult(id, text string, isError bool, extra Row) {
	fields := Row{"message": Row{"role": "user", "content": []Row{{"type": "tool_result", "tool_use_id": id, "content": text, "is_error": isError}}}}
	for k, v := range extra {
		fields[k] = v
	}
	t.row("user", fields)
}

// SkillCall is the model calling the Skill tool. A call that fails has no
// expansion row.
func (t *Transcript) SkillCall(skill, args, prompt string, fails bool) *Transcript {
	id := t.toolUse("Skill", Row{"skill": skill, "args": args})
	if fails {
		t.toolResult(id, "<tool_use_error>Skill "+skill+" is disabled for model invocation</tool_use_error>", true, nil)
		return t
	}
	t.toolResult(id, "Launching skill: "+skill, false, Row{"toolUseResult": Row{"success": true, "commandName": skill}})
	t.row("user", Row{"promptId": prompt, "isMeta": true, "sourceToolUseID": id,
		"message": Row{"role": "user", "content": []Row{{"type": "text", "text": "Base directory for this skill: /home/u/.claude/skills/" + skill + "\n\n# text"}}}})
	return t
}

// Bash is a Bash call and its result.
func (t *Transcript) Bash(cmd, result string) *Transcript {
	t.toolResult(t.toolUse("Bash", Row{"command": cmd}), result, false, nil)
	return t
}

// BashError is a Bash call whose result is an error.
func (t *Transcript) BashError(cmd, result string) *Transcript {
	t.toolResult(t.toolUse("Bash", Row{"command": cmd}), result, true, nil)
	return t
}

// BashBackground is a Bash call the tool ran in the background: its result
// arrives at once and says only that the command started.
func (t *Transcript) BashBackground(cmd string) *Transcript {
	t.toolResult(t.toolUse("Bash", Row{"command": cmd, "run_in_background": true}), "Command running in background with ID: b1", false, nil)
	return t
}

// BashPending is a Bash call with no result yet.
func (t *Transcript) BashPending(cmd string) *Transcript {
	t.toolUse("Bash", Row{"command": cmd})
	return t
}

// Read is the model reading a file.
func (t *Transcript) Read(path string, fails bool) *Transcript {
	t.toolResult(t.toolUse("Read", Row{"file_path": path}), "1\ttext", fails, nil)
	return t
}

// PRLink is the row Claude Code adds when a pull request is tied to the
// session. It repeats in real transcripts.
func (t *Transcript) PRLink(repo string, number int) *Transcript {
	t.Rows = append(t.Rows, Row{"type": "pr-link", "sessionId": "fixture", "prNumber": number,
		"prUrl": fmt.Sprintf("https://github.com/%s/pull/%d", repo, number), "prRepository": repo, "timestamp": t.stamp()})
	return t
}

// Title is the row holding the session's generated title.
func (t *Transcript) Title(title string) *Transcript {
	t.Rows = append(t.Rows, Row{"type": "ai-title", "aiTitle": title, "sessionId": "fixture"})
	return t
}

// Compaction is a compaction: the boundary, the summary that continues the
// conversation, and the attachment restating the skills invoked so far.
func (t *Transcript) Compaction(trigger string, sidechain bool, summary string) *Transcript {
	t.Rows = append(t.Rows, Row{"type": "system", "subtype": "compact_boundary", "isSidechain": sidechain, "timestamp": t.stamp(),
		"compactMetadata": Row{"trigger": trigger, "preTokens": 500000}})
	t.row("user", Row{"isCompactSummary": true, "isSidechain": sidechain, "message": Row{"role": "user", "content": summary}})
	t.Rows = append(t.Rows, Row{"type": "attachment", "isSidechain": sidechain, "timestamp": t.stamp(),
		"attachment": Row{"type": "invoked_skills", "skills": []Row{{"name": "review", "path": "userSettings:review",
			"content": "Base directory for this skill: /home/u/.claude/skills/review\n\n# text"}}}})
	return t
}

// Bytes returns the transcript as Claude Code writes it: one compact JSON
// object per line.
func (t *Transcript) Bytes() []byte {
	var buf bytes.Buffer
	for _, row := range t.Rows {
		line, err := json.Marshal(row)
		if err != nil {
			panic(err)
		}
		buf.Write(line)
		buf.WriteByte('\n')
	}
	return buf.Bytes()
}

// Write puts the transcript under projects as <project>/<id>.jsonl and
// returns the file's path.
func (t *Transcript) Write(tb testing.TB, projects, project, id string) string {
	tb.Helper()
	return WriteFile(tb, filepath.Join(projects, project, id+".jsonl"), t.Bytes())
}

func WriteFile(tb testing.TB, path string, data []byte) string {
	tb.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		tb.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		tb.Fatal(err)
	}
	return path
}

// ID returns a well-formed session id whose first characters are prefix.
func ID(prefix string) string {
	const blank = "00000000-0000-4000-8000-000000000000"
	return prefix + blank[len(prefix):]
}
